name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Release and Secrets"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Download Secrets Artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-secrets

    - name: Read secrets.json and set environment variables
      run: |
        secrets=$(cat secrets.json)
        echo "DOCKER_USERNAME=$(echo $secrets | jq -r '.DOCKER_USERNAME')" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=$(echo $secrets | jq -r '.DOCKER_PASSWORD')" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_URL=$(echo $secrets | jq -r '.DOCKER_IMAGE_URL')" >> $GITHUB_ENV
        echo "ENVIRONMENT=$(echo $secrets | jq -r '.ENVIRONMENT')" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin

    - name: Build and Tag Docker Image
      run: |
        docker build -t my-app:${{ env.ENVIRONMENT }} .
        docker tag my-app:${{ env.ENVIRONMENT }} ${{ env.DOCKER_IMAGE_URL }}:${{ env.ENVIRONMENT }}

    - name: Push Docker Image
      run: docker push ${{ env.DOCKER_IMAGE_URL }}:${{ env.ENVIRONMENT }}


