name: Deploy Dummy App to EC2

on:
  push:
    branches:
      - main

env:
  APP_NAME: dummy-app
  APP_PORT: 80

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Save EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Upload Project Files to EC2
        run: |
          scp -i ec2-key.pem -o StrictHostKeyChecking=no \
          -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/dummy-app

      - name: SSH and Build/Run Docker Container
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ~/dummy-app

            # Stop and remove previous container if exists
            docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true

            # Build the Docker image
            docker build -t ${{ env.APP_NAME }} .

            # Run the container (serve on port 80)
            docker run -d --name ${{ env.APP_NAME }} -p ${{ env.APP_PORT }}:80 ${{ env.APP_NAME }}
          EOF

      - name: Cleanup SSH Key
        run: rm ec2-key.pem
