name: Release

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches:
      - main  # Adjust the branch name if needed
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Adjust the Node.js version if needed

    - name: Install dependencies
      run: npm ci
      working-directory: ./myapp

    - name: Configure Git user
      run: |
        git config --global user.name "Purbae16"
        git config --global user.email "purbahassan@gmail.com"

    - name: Run release-it
      run: npx release-it --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
