name: Retrieve Secrets from Vault

on:
  push:
    branches:
      - main

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve Secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        id: vault
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: "token"
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
             kv/data/SemVer key1 ;
             kv/data/SemVer key2

      - name: Use the Retrieved Secrets
        run: |
          echo "Key1 value: ${{ steps.vault.outputs.key1 }}"
          echo "Key2 value: ${{ steps.vault.outputs.key2 }}"



