name: Retrieve Secrets from Vault

on:
  push:
    branches:
      - main

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve Secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: "token"
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: "kv/data/SemVer"

      - name: Use the Secret
        run: |
          echo "The secret is: $SECRET_VALUE"


          
          echo "SECRET_VALUE=$secret" >> $GITHUB_ENV

      - name: Use the Secret
        run: |
          echo "The secret is: $SECRET_VALUE"
